version: '3.8'

services:
  frontend:
    build:
      context: ../cf-ui
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      DB_USER: yourusername
      DB_PASSWORD: yourpassword
      DB_NAME: yourdatabase
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
